// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Idroid

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_uiLabelTime = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_main_240_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_x(ui_Image4, 0);
    lv_obj_set_y(ui_Image4, -1);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 272);

    ui_uiLabelTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiLabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelTime, -47);
    lv_obj_set_y(ui_uiLabelTime, -24);
    lv_obj_set_align(ui_uiLabelTime, LV_ALIGN_CENTER);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image4 = NULL;
    ui_uiLabelTime = NULL;

}
