// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_H
#define _UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

// SCREEN includes
#include "screens/ui_Screen1.h"

// COMPONENT includes
#include "components/ui_comp.h"

    // IMAGE includes
    extern const lv_img_dsc_t ui_img_66a0a92253e502c_png;

    void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
